image: gitlab/dind

stages:
- build

build:
  stage: build
  script:
  - docker info
  - docker login registry.gitlab.com -u gitlab-ci-token -p $CI_BUILD_TOKEN
  - docker build -t registry.gitlab.com/jim.andreasen/resume-site .
  - docker push registry.gitlab.com/jim.andreasen/resume-site

